homeassistant:
  customize: !include customize.yaml
  packages: !include_dir_named integrations
        
#######################################################
# Frontend
#######################################################
frontend:
  themes: !include_dir_merge_named themes
  javascript_version: latest

#######################################################
# Automations
#######################################################
automation: !include_dir_merge_list automations

#######################################################
# Configure a default setup of Home Assistant (frontend, api, etc)
#######################################################
default_config:

#######################################################
# Enable Python Scripts
#######################################################
python_script:

#######################################################
# Enable Stream
#######################################################
stream:

#######################################################
# Browser Mod
#######################################################
browser_mod: